### ISSUE TITLE
Unexpected Behavior in a Loop

### ISSUE THREAD

**Issue by brian-pond** [aeshirey/aeshirey.github.io#5]
Hi Adam,

Apologies in-advance for creating a GitHub Issue, in place you weren't expecting one.  Let me know if you'd rather communicate differently.

I've been learning about concurrent threads in Rust.  I started with The Book, and eventually encountered some very odd behavior.  Later, I discovered your Code Snippets page (_many thanks for the excellent work!_).  But then discovered the **same** odd behavior.

So I'm posting here, in the hopes you can either provide guidance.  Or at least confirm my findings.

### Step 1
I begin with your Arc + Mutex example below, **precisely** as you wrote it.
https://github.com/aeshirey/aeshirey.github.io/blob/master/_posts/2020-12-23-arc-mutex-in-rust.md

This works perfectly. :100: 

### Step 2
I want these threads to run forever, in an infinite loop.  Imagine this is some kind of "always on" background process.  Like a Windows service, or a Linux daemon.  Keep running these thread calculations indefinitely.

This is a simple modification.  I just add a `loop` to the closures' functions.
![image](https://user-images.githubusercontent.com/19827963/141693434-adaf30bd-23e7-477c-8802-0574dc2defa2.png)

This **also** works successfully.  :+1:   When I examine the output in my terminal, I can clearly see the 2 threads going back-and-forth, acquiring and dropping the lock.

![image](https://user-images.githubusercontent.com/19827963/141693932-b89f4634-cbce-4e37-92a4-ebf1ff4b6e1a.png)

I found it strange the threads don't always share time in a "balanced" way.  I imagined them swapping in a 1,2,1,2,1,2 rotation.  Instead, often a threads "keeps" their lock for a while, before giving it up.  I know part of the reason is the different values for each thread's `sleep` (750ms vs 1250ms).  Yet even when I use identical values for `sleep`, it's not a balanced act.  :shrug: 

But it **does** work!   I've sat and watched this in a terminal for 5+ minutes, and the program runs indefinitely, flipping between Thread 1 and Thread 2.  Which is fantastic.

### Step 3
This is where things break, and I get entirely lost.  I decided I want fewer `println!()` statements.  I want the application to be less chatty.

So I comment-out the following lines:
```
// println!("Thread 1 attempting to acquire lock...");
...
// println!("Thread 1 dropped lock");
...
// println!("Thread 2 attempting to acquire lock...");
...
// println!("Thread 2 dropped lock");
```

This is the **only** code change I make: just commenting-out those 4 `println!` macro statements.

Yet once done, the program abandons all "back and forth" behavior.  It tends to run a single Thread _indefinitely_.

![image](https://user-images.githubusercontent.com/19827963/141694189-3f6d9fef-72b3-4dd6-bec5-29f5d351d99d.png)

I've tested this repeatedly.  Yet I've only seen it swap threads just 1 time, over 10+ minutes of running. :disappointed: 

Any thoughts/ideas?  I expected the exclusion of `println!()` macros would be _entirely_ a non-issue.  Yet without them ,the program no longer trades time between threads.  As mentioned earlier, I achieved similar odd behavior following The Book, and writing code on my own, before encountering your excellent snippet example.

* My OS is Debian 11 "Bullseye".
* Linux kernel `Kernel: 5.10.0-9-amd64`
* My rustc is `rustc 1.56.0 (09c42c458 2021-10-18)`. 
* I'm building the binary using with Release:  `cargo run --release`

Thanks,
Brian

**Comment by aeshirey** [comment]
I'm no expert, but...

The example code I wrote is quite simple - too simple, in fact, because the simulated work inside the critical section is all that happens in the thread. There's nothing else besides a few `println!` statements. And that's the key here to your question: the I/O that is incurred by `println!` is nontrivial, and it gives enough time in one thread that the other is able to acquire the mutex's lock. This has the effect of handing the lock back and forth between the two threads.

When your looping code doesn't `println!`, one of the threads (almost certainly thread 1 because it's the first one that is spawned) can _immediately_ acquire the lock and start its 'work'. (In the meantime, thread 2 is waiting to acquire the mutex lock.) Thread 1 finishes its work, releases the lock, and loops back to an immediate lock request. My assumption is that the delay between thread 1 dropping and re-requesting a lock is very nearly zero while thread 2 probably(?) has some sort of OS-imposed delay between its repeated lock requests. That it only switches for you once in 10 minutes probably means that thread 2 just so happened to sneak in before thread 1 pick it back up, at which point the tables are turned and now thread 2 monopolizes access.

In practice, you shouldn't have this problem because your critical section (protected by the mutex's guard) should be a very small part of the work being done in the thread. Otherwise (and as the code is basically done now), you just have two tasks running _serially_ but with indeterminate ordering (but probably thread 1 first then 2).

Does that make sense? I'm happy to explain better or otherwise help to the extent I'm able.

**Comment by aeshirey** [comment]
I hope this was helpful, Brian. If this wasn't clear or if you have any other questions, let me know -- I'm happy to help.

**Comment by brian-pond** [comment]
Thanks, Adam!  Yes, it was quite helpful.  I'm actually making a bit of progress in this area.

I believe the key to success is this:

1. Ensure I undo the locks immediately once they're no-longer-needed.  Either by enclosing the related code in a new, inner scope.  Or explicitly performing an unlock in the correct place.

2. I should not place the `thread:sleep()` **inside** the scope of the lock.  I believe that's my problem in the original code I posted above.  The thread is sleeping within the `if let...lock()` statement.  Therefore, during the whole time of the sleep, the lock is still engaged.  Leaving *very* little time for the other thread to compete, and gain its own lock.

Armed with this new knowledge, I've now got my program running 3 separate threads in tandem.  I've left it running on my laptop in the background for several days...flawless execution. :smiley_cat:
